server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fakebook
    username: huuhoai
    password: mysql2655
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
