server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fakebook
    username: root
    password: vvhynol806
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.springframework.security: DEBUG