server:
  port:${BE_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_NAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.springframework.security: DEBUG
