server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://database:3306/fakebook
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      root: DEBUG
